In [ ]:
#Demonstrate use of tensorflow and pytorch by implementing simple code in python

#PROGRAM USING TENSORFLOW
!pip install tensorflow
# import
import tensorflow as tf
import numpy as np
a = tf.constant(15)
b = tf.constant(20)
print(a+b)
# input
x = np.random.rand(100).astype(np.float32)
print(x)
# output - observed
y = x * 0.2 + 0.2
# Weight
W = tf.Variable(tf.random.normal([1]))
# bias
b = tf.Variable(tf.zeros([1]))
# Create a function for MSE - mean squared error
def mse_loss():
  ypred = W * x + b
  loss = tf.reduce_mean(tf.square(ypred-y))
  return loss
# Optimizer
optimizer = tf.keras.optimizers.Adam()
# Iterations
for step in range(5000):
  optimizer.minimize(mse_loss,var_list=[W,b])
  if step % 500 == 0:
    print(step, W.numpy(), b.numpy())

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
tf.Tensor(35, shape=(), dtype=int32)
[0.91604614 0.2656876  0.8224223  0.50452656 0.3479574  0.3400962
 0.9616694  0.25592774 0.5595731  0.47071338 0.7488815  0.23279174
 0.4475779  0.401386   0.18703842 0.62297577 0.5874871  0.89879954
 0.9138704  0.3013523  0.8635902  0.44028348 0.29578784 0.46097982
 0.67583126 0.7873803  0.9116637  0.71900785 0.72530025 0.9111742
 0.17575009 0.17874509 0.03600221 0.5087037  0.34312275 0.95067865
 0.7217339  0.7112802  0.37893105 0.48096442 0.8421739  0.23785542
 0.9650131  0.60659266 0.05334562 0.89164376 0.09129342 0.14613593
 0.8402736  0.05540596 0.09451262 0.30798975 0.39687997 0.02470804
 0.46443424 0.14867625 0.50721776 0.57937604 0.5030732  0.08356942
 0.9934773  0.71622604 0.90874463 0.44679245 0.38881508 0.06343974
 0.27983314 0.02809873 0.70671844 0.33213902 0.07458501 0.53903866
 0.09316872 0.7154719  0.81544423 0.84808373 0.68995166 0.2615

In [ ]:
#PROGRAM USING PYTORCH

import torch
import numpy as np
data = [
[1,2],
[3,4]
]
x_data = torch.tensor(data)
print(type(x_data))
### 2 - using numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)
print(type(x_np))
### 3 - using another tensor
x_ones = torch.ones_like(x_data)
print("One Tensor: \n",x_ones)
x_rand = torch.rand_like(x_data,dtype=torch.float)
print(x_rand)
#### more ways to create tensors
shape = (2,3)
random_tensor = torch.rand(shape)
print(random_tensor)
print(type(random_tensor))
ones_tensor = torch.ones(shape)
print(ones_tensor)
print(type(ones_tensor))
zeros_tensor = torch.zeros(shape)
print(zeros_tensor)
print(type(zeros_tensor))
tensor = torch.rand(3,4)
print(tensor)
tensor.shape
tensor.dtype
tensor.device
# Tensor Operations
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print("Device tensor is stored in ", tensor.device)
# Indexing, Slicing
tensor = torch.ones(4,4)
print(tensor)
print(tensor)
tensor1 = torch.zeros(4,4)
print(tensor1)
tensor2 = torch.cat([tensor,tensor1])
print(tensor2)
# Multiply Operation
tensor.mul(tensor1)
tensor * tensor1
tensor.T
# inplace - change the original tensor
tensor.add_(3)
print(tensor)
# from tensor to numpy
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)
print(type(n))

<class 'torch.Tensor'>
tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>
One Tensor: 
 tensor([[1, 1],
        [1, 1]])
tensor([[0.9283, 0.4584],
        [0.6359, 0.3182]])
tensor([[0.5786, 0.6851, 0.4865],
        [0.8180, 0.5528, 0.9398]])
<class 'torch.Tensor'>
tensor([[1., 1., 1.],
        [1., 1., 1.]])
<class 'torch.Tensor'>
tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>
tensor([[0.1987, 0.7374, 0.7012, 0.1647],
        [0.2086, 0.6823, 0.3574, 0.6515],
        [0.3657, 0.3679, 0.8492, 0.4230]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 